In [1]:
import numpy as np

In [3]:
v=np.array([[1,2,3,4],[5,6,7,8]])
v

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [4]:
v.shape

(2, 4)

In [5]:
v[0][1]

2

In [8]:
v.size

8

In [14]:
v.ndim

2

In [15]:
np.array([34,5,62,53],ndmin=20)

array([[[[[[[[[[[[[[[[[[[[34,  5, 62, 53]]]]]]]]]]]]]]]]]]]])

In [16]:
np.array([34,5,62,53],dtype=complex)

array([34.+0.j,  5.+0.j, 62.+0.j, 53.+0.j])

In [24]:
np.array([(3,4),(35,63)])

array([[ 3,  4],
       [35, 63]])

In [66]:
m=np.array([(3,4),(35,63)],dtype=[('a','<i4'),('b','<i8')]) #i1=int8, i2=int16, i4=int32, i8=int64
m

array([( 3,  4), (35, 63)], dtype=[('a', '<i4'), ('b', '<i8')])

In [67]:
type(m[0][0])

numpy.int32

In [68]:
type(m[0][1])

numpy.int64

In [69]:
type(m[1][0])

numpy.int32

In [70]:
type(m[1][1])

numpy.int64

In [40]:
m=np.mat([3,46,34,5])
m

matrix([[ 3, 46, 34,  5]])

In [41]:
np.array([3,54,35,6])

array([ 3, 54, 35,  6])

In [42]:
np.array(m) #matrix converted to array

array([[ 3, 46, 34,  5]])

In [43]:
np.asanyarray([3,54,35,6])

array([ 3, 54, 35,  6])

In [47]:
#asanyarray does not convert a list which is alreay in some form of array(here m is a matrix)
np.asanyarray(m) #matrix not converted to array

matrix([[ 3, 46, 34,  5]])

In [49]:
a=np.array([2,3,5,7])
a

array([2, 3, 5, 7])

In [53]:
b=a #Swallow copy
b

array([9, 3, 5, 7])

In [54]:
b[0]=9
b

array([9, 3, 5, 7])

In [55]:
a

array([9, 3, 5, 7])

In [56]:
c=np.copy(a) #deep copy
c

array([9, 3, 5, 7])

In [57]:
c[0]=45
c

array([45,  3,  5,  7])

In [58]:
a

array([9, 3, 5, 7])

In [61]:
np.fromfunction(lambda x,y: x**2==y,(3,4)) #indexing of rows and column is from 0 to n-1 by default

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False, False, False]])

In [63]:
np.fromstring('2 4 5',sep=' ')

array([2., 4., 5.])

In [65]:
np.fromstring('3,4,5',dtype=int,sep=',')

array([3, 4, 5])

In [72]:
np.arange(34.43)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25.,
       26., 27., 28., 29., 30., 31., 32., 33., 34.])

In [76]:
o=np.arange(0,34.43,0.8)
l=list(o)

In [78]:
o

array([ 0. ,  0.8,  1.6,  2.4,  3.2,  4. ,  4.8,  5.6,  6.4,  7.2,  8. ,
        8.8,  9.6, 10.4, 11.2, 12. , 12.8, 13.6, 14.4, 15.2, 16. , 16.8,
       17.6, 18.4, 19.2, 20. , 20.8, 21.6, 22.4, 23.2, 24. , 24.8, 25.6,
       26.4, 27.2, 28. , 28.8, 29.6, 30.4, 31.2, 32. , 32.8, 33.6, 34.4])

In [79]:
type(l)

list

In [82]:
np.linspace(3,7,20)

array([3.        , 3.21052632, 3.42105263, 3.63157895, 3.84210526,
       4.05263158, 4.26315789, 4.47368421, 4.68421053, 4.89473684,
       5.10526316, 5.31578947, 5.52631579, 5.73684211, 5.94736842,
       6.15789474, 6.36842105, 6.57894737, 6.78947368, 7.        ])

In [83]:
np.linspace(3,7,20).reshape(5,4)

array([[3.        , 3.21052632, 3.42105263, 3.63157895],
       [3.84210526, 4.05263158, 4.26315789, 4.47368421],
       [4.68421053, 4.89473684, 5.10526316, 5.31578947],
       [5.52631579, 5.73684211, 5.94736842, 6.15789474],
       [6.36842105, 6.57894737, 6.78947368, 7.        ]])

In [94]:
np.linspace(3.5,5.5,endpoint=False,retstep=True)

(array([3.5 , 3.54, 3.58, 3.62, 3.66, 3.7 , 3.74, 3.78, 3.82, 3.86, 3.9 ,
        3.94, 3.98, 4.02, 4.06, 4.1 , 4.14, 4.18, 4.22, 4.26, 4.3 , 4.34,
        4.38, 4.42, 4.46, 4.5 , 4.54, 4.58, 4.62, 4.66, 4.7 , 4.74, 4.78,
        4.82, 4.86, 4.9 , 4.94, 4.98, 5.02, 5.06, 5.1 , 5.14, 5.18, 5.22,
        5.26, 5.3 , 5.34, 5.38, 5.42, 5.46]),
 0.04)

In [98]:
np.zeros((2,4,5))

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [99]:
np.ones((2,3,4))+1

array([[[2., 2., 2., 2.],
        [2., 2., 2., 2.],
        [2., 2., 2., 2.]],

       [[2., 2., 2., 2.],
        [2., 2., 2., 2.],
        [2., 2., 2., 2.]]])

In [102]:
np.empty((2,4)) #gives random values close to zero

array([[0.00e+000, 0.00e+000, 0.00e+000, 0.00e+000],
       [0.00e+000, 6.48e-321, 0.00e+000, 0.00e+000]])

In [104]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [105]:
np.logspace(5.6,7.8,6,base=2)

array([ 48.50293013,  65.79928491,  89.26359465, 121.09537878,
       164.27851489, 222.8609442 ])

In [106]:
np.random.rand(4,5)

array([[0.39251016, 0.14654862, 0.35888957, 0.28633505, 0.91481371],
       [0.75057229, 0.11507153, 0.63466748, 0.82607025, 0.46851096],
       [0.97660125, 0.20476227, 0.88579393, 0.38323254, 0.91989474],
       [0.57922288, 0.0680227 , 0.71259576, 0.93182605, 0.83853997]])

In [107]:
np.random.rand(4,5).reshape(5,-25234)

array([[0.38625337, 0.55288122, 0.87589898, 0.18188539],
       [0.02929843, 0.74019591, 0.08712281, 0.12297927],
       [0.02675227, 0.16827723, 0.40356155, 0.79525768],
       [0.57612734, 0.26956982, 0.34314205, 0.89172591],
       [0.49863787, 0.54811494, 0.54688406, 0.57079656]])

In [108]:
np.random.randn(4,5)

array([[ 0.17732887,  0.18522476, -1.37592807,  1.30601956,  0.06286005],
       [ 3.13345238,  1.42698222, -1.22409864, -0.39513112, -0.02367518],
       [-1.14354372, -0.19259177,  1.39103464, -0.53092131,  0.11420353],
       [-1.3600924 ,  0.42473622,  0.56959547,  1.50214008,  1.36860791]])

In [110]:
np.random.randint(4,10,(5,6))

array([[4, 6, 7, 9, 8, 8],
       [9, 4, 9, 9, 9, 6],
       [9, 4, 9, 6, 7, 4],
       [8, 7, 4, 4, 7, 8],
       [9, 8, 7, 7, 6, 7]])

# * is used for index wise multiplication
# @ is used for matrix multiplication

In [115]:
n=np.zeros((4,4))
n

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [122]:
m=np.array([[1,3,4,2]])
m

array([[1, 3, 4, 2]])

In [123]:
n+m

array([[1., 3., 4., 2.],
       [1., 3., 4., 2.],
       [1., 3., 4., 2.],
       [1., 3., 4., 2.]])

In [124]:
m=np.array([[1,3,4,2]]).T
m

array([[1],
       [3],
       [4],
       [2]])

In [126]:
p=n+m
p

array([[1., 1., 1., 1.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [2., 2., 2., 2.]])

In [127]:
np.sqrt(p)

array([[1.        , 1.        , 1.        , 1.        ],
       [1.73205081, 1.73205081, 1.73205081, 1.73205081],
       [2.        , 2.        , 2.        , 2.        ],
       [1.41421356, 1.41421356, 1.41421356, 1.41421356]])

In [131]:
np.mod(p,4)

array([[1., 1., 1., 1.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [2., 2., 2., 2.]])